# configfile: "./snake_config.yaml"

database_dir = "../database"
# INFOJSONS, = glob_wildcards(f"{database_dir}/info_jsons/"+"{info_json}.json")
FASTAS, = glob_wildcards(f"{database_dir}/clustered_ldo_fastas/"+"{fasta}.fasta")

rule all:
    input:
        expand(f"{database_dir}/alignments/"+"{fasta}_clustered_ldos_aln.fasta", fasta=FASTAS),

rule mafft:
    input:
        f"{database_dir}/clustered_ldo_fastas/"+"{fasta}.fasta"
    output:
        f"{database_dir}/alignments/"+"{fasta}_clustered_ldos_aln.fasta"
    threads: 6
    shell:
        "mafft --thread {threads} --quiet --anysymbol {input} > {output}"
